coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%

codecov:
  notify:
    require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "src/test/**"
  - "target/**"
  - "logs/**"
  - "*.md"

coverage:
  round: down
  precision: 2
  range: "70...100"
