name: CI

on:
  push:
    branches:
      - "main"
      - "master"
      - "tests/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "tests/**"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ '25' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Build, test and coverage check (verify)
        run: |
          mvn -B -U -fae -DtrimStackTrace=false verify

      - name: Upload Surefire reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.os }}-jdk${{ matrix.java }}
          path: |
            target/surefire-reports/**
            **/target/surefire-reports/**
          if-no-files-found: warn

      - name: Upload JaCoCo coverage report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-${{ matrix.os }}-jdk${{ matrix.java }}
          path: |
            target/site/jacoco/**
            **/target/site/jacoco/**
            target/jacoco.exec
            **/target/jacoco.exec
          if-no-files-found: warn

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.java == '25'
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
